language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  # Rubinius in 1.8 mode on Travis does not work. It complains about st_data_t etc.
  #- rbx-18mode
  - rbx-19mode
install: env NOEXEC=skip bundle install --without=documentation && rake travis:setup --trace
script: bundle exec rake spec --trace
