os:
  - osx

language: ruby
cache: bundler
rvm:
  - system

before_install:
  # There is a bug in travis. When using system ruby, bundler is not installed
  # and causes the default install action to fail.
  - sudo gem install bundler

addons:
 code_climate:
   repo_token: fcf708528e1eca6e8a8bf8f7be3bd24e4478b019c4cd7860325c141dd52aa152 

