language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
install: env NOEXEC=skip bundle install --without=documentation && rake travis:setup --trace
script: bundle exec rake spec --trace
